### ISSUE TITLE
Update build configuration script for DOS/Windows

### ISSUE THREAD

**Issue by BrianKnoblauch** [m2sf/m2pp#2]
M2PP build configuration script for DOS/Windows at: https://github.com/m2sf/m2pp/tree/master/cfg needs to be updated as the available choices on Windows will be different than those on Unix/Posix system (which can be found at: https://github.com/m2sf/m2pp/blob/master/cfg/config.sh for checking completeness)

"Available ISO compilers on Windows/DOS are ADW and XDS. Available PIM compilers are FST, GPM and Logitech but they can all be handled under option "Generic PIM Compiler". Then there is the GPM compiler which runs on .NET...

For ISO compilers we can configure using the ISO IO library  ...  For PIM compilers the IO library will simply be the PIM IO library. GPM has its own IO library."

**Comment by trijezdci** [comment]
Correction: FST and Logitech (and other PIM compilers) can be handled with option "Generic PIM Compiler" but GPM cannot and must have its own option (and configuring the GPM specific IO library files).

**Comment by trijezdci** [comment]
I don't think there is any POSIX based IO library on Windows.

When choosing ISO as a dialect, the compiler choices are ADW and XDS (for now, we'll eventually need to add Clarion, too) and the library choices are ISO IO library and Windows IO library (calling the OS directly via shim libraries using the foreign function interface support).

When choosing PIM as a dialect, there is no compiler choice since all Windows/DOS compilers can be supported with a generic PIM configuration, thus the "choice" will default to "Generic PIM Compiler" but the user shouldn't need to select this. Likewise, for PIM there is only one choice of library, the PIM IO library and consequently it should default to that and the user shouldn't need to select it. However, these default "choices" should be displayed in the final summary.

For GPM, since it is neither strictly PIM nor strictly IO and has its own library, it is indeed OK to list it as a "dialect". Thus, when GPM is selected, there is no need to let the user choose a compiler and library. The compiler choice should default to "GPM" and the library choice should default to "vendor IO library". Again, this needs to be displayed in the final summary.

hope this clarifies

**Comment by BrianKnoblauch** [comment]
DOS/Windows config script is now functional, so have merged in.  I will of course seek to make the clunkier parts of it more elegant if/when better solutions present themselves.

**Comment by trijezdci** [comment]
Hi Brian,

On Fri, 25 Sep 2020 at 09:21, Brian Knoblauch <notifications@github.com>
wrote:

> DOS/Windows config script is now functional, so have merged in.
>
great, thanks.


> I will of course seek to make the clunkier parts of it more elegant
> if/when better solutions present themselves.
>
I think the structure is alright as it is, no need to beautify this, we
better focus our efforts on the compiler.

However, I noticed that the script copies the stdio and unistd files. There
are POSIX specific low-level IO libraries. I don't think those will be
needed on Windows nor on DOS systems. Perhaps if somebody uses cygwin and
compiles the project with a POSIX based compiler, but we don't actually
cover that eventuality and this would require further study. We can look
into this at some later time. For now, we should ignore this scenario.

For WIndows (and possibly DOS) we probably want to implement Windows/DOS
versions of the files

BasicFileIO.mod
BasicFileSys.mod

which then call Windows/DOS I/O APIs directly and bypass the PIM or ISO I/O
libraries.

That would be something to look into and then add the appropriate copy and
remove commands to the script when those files are available.

However, at this point I think the Windows/DOS implementation of the
Pathname library is more important because those are required to get both
M2PP and M2BSK going.


regards
benjamin

**Comment by BrianKnoblauch** [comment]
I was going to remove the stdio / unistd sections as I e-mailed a short time ago (in direct reply to your above comment), but then I took a closer look at the code.  It's doing a remove of those files rather than a copy.  I imagine the remove was designed to make sure they don't get compiled in on this platform which does not require them, which would make the action correct.  I'm not sure how I feel about removing files in a way that can't be reversed by a clean though.  I suppose it's OK in this case, as there are no DOS/Windows compilers that would use them in any configuration.

**Comment by trijezdci** [comment]
>
> I was going to remove the stdio / unistd sections as I e-mailed a short
> time ago (in direct reply to your above comment), but then I took a closer
> look at the code. It's doing a remove of those files rather than a copy. I
> imagine the remove was designed to make sure they don't get compiled in on
> this platform which does not require them, which would make the action
> correct.
>
This is correct when building on a Unix platform where the Unix version of
the configuration script may have run before and copied these files into
the build directory. However, the Unix version of the script cannot be run
on a DOS/Windows platform and therefore, these files would not have been
copied into the build directory in the first place.


> I'm not sure how I feel about removing files in a way that can't be
> reversed by a clean though. I suppose it's OK in this case, as there are no
> DOS/Windows compilers that would use them in any configuration.
>
Correct.
